### ISSUE TITLE
Builder query execution error in Laravel 8.x

### ISSUE THREAD

**Issue by deeppanara** [asseco-voice/laravel-json-query-builder#33]
DB : MariaDb
Leavel : 8.x

Issue in query syntax created by "JsonQuery" will give column and table name in double quote which is not supported but mysql and MariaDB as well.

```
public $builder;
    public function __construct()
    {
        $this->builder = app(Builder::class);
        $this->builder->setModel(new User());
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index(Request $request)
    {
        $input = [
            'search' => [
                'first_name' => '=Simeon',
            ],
        ];
        $jsonQuery = new JsonQuery( $this->builder , $input);
        $jsonQuery->search();
        dd($this->builder->get());
        return UserResource::collection($users);
    }
```
Error

`Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"users" where ((("first_name" in (?))))' at line 1 (SQL: select * from "users" where ((("first_name" in ("Simeon"))))) in file /var/www/api/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 692`

mysql accept this type of syntax

```
SQL: select * from `users` where (((`first_name` in ("Simeon"))))
```

**Comment by Norgul** [comment]
Quotes should not be an issue in MariaDb, I am using it all the time. Which version of MariaDb are you running?

**Comment by Norgul** [comment]
The error is that you're calling the method wrong. Instead of instantiating builder and new `User` model, try this:
```php
$this->builder = User::query();
```

Also, [this](https://github.com/asseco-voice/laravel-json-search) is a package using this package, and it essentially enables the search method on your eloquent models.
